### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by skeydan** [agrinh/procyclist_performance#1]
Hi,

very nice paper! Is the dataset available somewhere?

Thanks!

**Comment by agrinh** [comment]
Sorry about the late reply. Thanks! Unfortunately, due to privacy concerns we're not able to release the dataset. I've been considering creating a dummy dataset for easier re-use of the code and might do that in the future if more people are interested.

**Comment by Denebulas** [comment]
Thank you it helps a lot.
I am still not able to figure out what is the format of a .mat file, for example where the name of the matrix goes and what is the separator and so on without examples.
maybe a (sanitized) <cyclist name>.mat and <session>.mat files example would help.
Also the format for timesteps is unpecified.
Thanks, again
Gabriel
