### ISSUE TITLE
Error in dry run the code

### ISSUE THREAD

**Issue by Atul997** [agrinh/procyclist_performance#4]
I am running the code just by putting a file inside the folder /data/men but I am getting error of 

`Traceback (most recent call last):
  File "train.py", line 243, in <module>
    main()
  File "train.py", line 218, in main
    sessions = procyclist.dataset.load()
  File "/home/atul/Downloads/code1/cyclist/lib/python3.5/site-packages/procyclist-1-py3.5.egg/procyclist/dataset.py", line 49, in load
    parameters=parameters
  File "/home/atul/Downloads/code1/cyclist/lib/python3.5/site-packages/procyclist-1-py3.5.egg/procyclist/sessions.py", line 195, in create
    cyclists = os.listdir(dataset_path)
FileNotFoundError: [Errno 2] No such file or directory: '/data/men'`

Can you please point out what I am missing here

**Comment by azamat-tyulebayev** [comment]
Remove the / before data/men in sessions.cfg

I had the same issue. At this point, I'm not sure the developer tested this... Maybe it has to do with using different operating systems.

**Comment by agrinh** [comment]
Sorry for the slow reply, the path `/data/men` is simply what we used, you can set it to whichever absolute path where you have your data in the [sessions.cfg](https://github.com/agrinh/procyclist_performance/blob/master/procyclist/config/sessions.cfg). Which sections to use in that file (example / men / women) can be chosen in [dataset.py#L47](https://github.com/agrinh/procyclist_performance/blob/2bae4f1d91d8276461d426d4f5330cf3bdeb27ed/procyclist/dataset.py#L47)

I've added some instructions to the [README.md](https://github.com/agrinh/procyclist_performance#collection-of-sessions) that hopefully explains how to use it . Can you take a look and see if it answers your question?

Also if you are using Windows you might want to set it to something like `C:\path\to\data`.

**Comment by Atul997** [comment]
Thanks for reply. I resolved it by my own.
I came out of one folder and ran it and worked perfectly.

**Comment by agrinh** [comment]
@Atul997 good to hear! I'll close this issue now.

On another note, if you've happened to create some test data which you could run this with I'd really appreciate if you could share it (PR would be great).
